import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";
import type { UserThemeConfig as DocSearchThemeConfig } from "@docsearch/docusaurus-adapter";
import type { ScalarOptions } from "@scalar/docusaurus";
import { BundledLanguage, bundledLanguages } from "shiki";
import type { MDXPlugin } from "@docusaurus/mdx-loader";
import rehypeShiki, { RehypeShikiOptions } from "@shikijs/rehype";
import {
  transformerMetaHighlight,
  transformerNotationDiff,
  transformerNotationHighlight,
  transformerNotationWordHighlight,
  transformerNotationFocus,
} from "@shikijs/transformers";

import { rendererClassic, transformerTwoslash } from "@shikijs/twoslash";
import {
  NormalizedSidebar,
  NormalizedSidebarItem,
  SidebarItemsGeneratorVersion,
  SidebarItemCategory,
} from "@docusaurus/plugin-content-docs/src/sidebars/types.js";
import { llmsRootContent } from "./src/content/llms-root-content";
import { createRedirects } from "./redirects";

function isErrorFromVersionedDocs(options: { meta?: { __raw?: string } }) {
  if (options.meta?.__raw?.includes("loc=")) {
    const locMatch = options.meta.__raw.match(/loc=([^\s]+)/);
    if (locMatch[1]?.includes("versioned_docs")) {
      return true;
    }
  }
  return false;
}

const rehypeShikiPlugin = [
  rehypeShiki,
  {
    themes: {
      light: "catppuccin-latte",
    },
    langs: Object.keys(bundledLanguages) as BundledLanguage[],
    transformers: [
      transformerTwoslash({
        renderer: rendererClassic(),
        onTwoslashError(error, code, lang, options) {
          const isVersionedDocs = isErrorFromVersionedDocs(options);
          if (isVersionedDocs) {
            return; // Ignore versioned docs
          }
          throw error;
        },
      }),
      transformerMetaHighlight(),
      transformerNotationWordHighlight(),
      transformerNotationDiff(),
      transformerNotationHighlight(),
      transformerNotationFocus(),
    ],
  } satisfies RehypeShikiOptions,
] satisfies MDXPlugin;

type CustomInjectedCategory = Omit<SidebarItemCategory, "items"> & {
  items: any;
};

function injectTypeDocSidebar(
  version: SidebarItemsGeneratorVersion,
  items: NormalizedSidebar,
): NormalizedSidebar {
  return items.map((item) => {
    if (item.customProps?.id === "generated-api" && item.type === "category") {
      const injectedItems: (CustomInjectedCategory | NormalizedSidebarItem)[] =
        [
          {
            type: "category",
            label: "React Native SDK",
            link: { type: "doc", id: "api/mobile/index" },
            items: require(
              `${version.contentPath}/api/mobile/typedoc-sidebar.cjs`,
            ),
          },
          {
            type: "category",
            label: "React SDK",
            link: { type: "doc", id: "api/web/index" },
            items: require(
              `${version.contentPath}/api/web/typedoc-sidebar.cjs`,
            ),
          },
          {
            type: "category",
            label: "Server SDK for JS",
            link: { type: "doc", id: "api/server/index" },
            items: require(
              `${version.contentPath}/api/server/typedoc-sidebar.cjs`,
            ),
          },
        ];

      injectedItems.push({
        type: "category",
        label: "Server SDK for Python",
        items: [
          {
            type: "autogenerated",
            dirName: "api/server-python",
          },
        ],
      });

      return {
        ...item,
        items: [
          ...injectedItems,
          ...item.items.filter((element) => element.type === "doc"),
        ] as NormalizedSidebar,
      };
    }

    return item;
  });
}

const typedocConfig = {
  readme: "none",
  parametersFormat: "table",
  propertyMembersFormat: "table",
  typeDeclarationFormat: "list",
  excludeExternals: "true",
  tableColumnSettings: {
    hideSources: true,
  },
  categoryOrder: [
    "Connection",
    "Devices",
    "Screenshare",
    "Component",
    "*",
    "Debugging",
  ],
  sort: ["kind", "alphabetical"],
  kindSortOrder: ["Method", "Function"],
};

const config: Config = {
  title: "Fishjam Docs",
  tagline: "Easiest way to add video streaming to your React Native app",
  favicon: "img/favicon.svg",
  // Set the production url of your site here
  url: "https://documentation.fishjam.io/",
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: "/docs",
  trailingSlash: false,

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: "fishjam-cloud",
  projectName: "documentation",

  onBrokenLinks: "log",
  onBrokenAnchors: "log",
  onDuplicateRoutes: "throw",

  // Ask-AI sidepanel config (rendered in src/theme/Root.tsx via @docsearch/react).
  // Lives here because themeConfig now uses `algolia` (for t-rex's search) rather
  // than the @docsearch adapter's `docsearch` key.
  customFields: {
    askAi: {
      appId: "IBX716Q0KT",
      apiKey: "5dcaa347f57ca14f8cb59926164dd129",
      indexName: "Fishjam",
      assistantId: "49fdf088-e614-4b89-86c2-da8c4b566260",
      agentStudio: true,
    },
  },

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  markdown: {
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: "log",
    },
  },
  themes: ["@docusaurus/theme-mermaid"],

  future: {
    v4: true,
    // Docusaurus is pinned to 3.9.2 to match @swmansion/t-rex-ui (it imports 3.9-only
    // theme-common internals). On 3.9.x this key is `experimental_faster`; it became
    // `faster` in 3.10. Rename back if Docusaurus is ever upgraded.
    experimental_faster: {
      swcJsLoader: true,
      swcJsMinimizer: true,
    },
  },

  presets: [
    [
      "classic",
      {
        docs: {
          sidebarPath: "./sidebars/docs.ts",
          path: "docs",
          routeBasePath: "/",
          editUrl: ({ versionDocsDirPath, docPath }) =>
            `https://github.com/fishjam-cloud/documentation/tree/main/${versionDocsDirPath}/${docPath}`,
          beforeDefaultRehypePlugins: [],
          rehypePlugins: [rehypeShikiPlugin],
          remarkPlugins: [
            [require("@docusaurus/remark-plugin-npm2yarn"), { sync: true }],
            require("./src/remark/inject-file-path.mjs"),
          ],
          async sidebarItemsGenerator({
            defaultSidebarItemsGenerator,
            ...args
          }) {
            const items = await defaultSidebarItemsGenerator(args);
            return injectTypeDocSidebar(args.version, items);
          },
        },
        theme: {
          customCss: "./src/css/custom.css",
        },
        googleTagManager: {
          containerId: "GTM-5L68C9JS",
        },
        sitemap: {
          lastmod: "date",
          changefreq: "weekly",
          filename: "sitemap.xml",
        },
      } satisfies Preset.Options,
    ],
    // Software Mansion premium docs theme. Placed after classic so it can
    // override theme components. llms:false — we already run docusaurus-plugin-llms.
    [require.resolve("@swmansion/t-rex-ui/preset"), { llms: false }],
  ],

  themeConfig: {
    image: "img/social-card.png",
    colorMode: {
      defaultMode: "light",
      disableSwitch: true,
    },
    navbar: {
      logo: {
        alt: "Fishjam",
        src: "img/logo.svg",
      },
      items: [
        {
          type: "doc",
          docId: "index",
          label: "Docs",
          position: "left",
        },
        {
          to: "/api/rest",
          label: "API Reference",
          position: "left",
        },
        {
          type: "docsVersionDropdown",
          position: "right",
        },
        {
          href: "https://fishjam.io/app/",
          label: "Fishjam Dashboard",
          position: "right",
        },
        {
          href: "https://github.com/fishjam-cloud",
          label: "GitHub",
          position: "right",
        },
      ],
    },
    // Search: classic Algolia DocSearch via @docusaurus/theme-search-algolia
    // (registered in `themes`). t-rex's navbar search bar and search page read
    // themeConfig.algolia directly. We use this instead of the
    // @docsearch/docusaurus-adapter plugin because the adapter forbids
    // themeConfig.algolia alongside its `docsearch` key, and t-rex's navbar search
    // requires `algolia`. The Ask-AI sidepanel keys moved to customFields.askAi
    // (consumed by src/theme/Root.tsx -> AskAiSidepanel, which uses @docsearch/react).
    algolia: {
      appId: "IBX716Q0KT",
      apiKey: "5dcaa347f57ca14f8cb59926164dd129",
      indexName: "Fishjam",
      contextualSearch: true,
      searchPagePath: "search",
    },
    footer: {
      links: [
        {
          title: "Quick Setup",
          items: [
            {
              label: "React Native",
              to: "/tutorials/react-native-quick-start",
            },
            {
              label: "React",
              to: "/tutorials/react-quick-start",
            },
            {
              label: "Backend",
              to: "/tutorials/backend-quick-start",
            },
          ],
        },

        {
          title: "More",
          items: [
            {
              label: "Fishjam",
              to: "https://fishjam.io",
            },
            {
              label: "GitHub",
              href: "https://github.com/fishjam-cloud",
            },
            {
              label: "Software Mansion",
              href: "https://swmansion.com/",
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Software Mansion, Inc. All trademarks and copyrights belong to their respective owners.`,
    },
  } satisfies Preset.ThemeConfig & DocSearchThemeConfig,

  plugins: [
    // t-rex-ui ships its theme as untranspiled JSX under node_modules. Docusaurus's
    // JS rule excludes node_modules from transpilation (it only un-excludes
    // "docusaurus"-named packages), so the build fails to parse t-rex's theme/*.js
    // (e.g. theme/MDXContent, theme/DocItem/Layout). Run just that theme dir through
    // Docusaurus's own JS loader. The core rule already excludes it, so no double
    // compilation. (t-rex's own docs dodge this because there the theme is a
    // monorepo workspace, i.e. resolved outside node_modules.)
    function transpileTRexUiTheme() {
      return {
        name: "transpile-t-rex-ui-theme",
        configureWebpack(_config: unknown, isServer: boolean, utils: any) {
          return {
            module: {
              rules: [
                {
                  test: /\.jsx?$/,
                  include: [/[/\\]@swmansion[/\\]t-rex-ui[/\\]theme[/\\]/],
                  use: [utils.getJSLoader({ isServer })],
                },
              ],
            },
          };
        },
      };
    },
    ["@docusaurus/plugin-client-redirects", { createRedirects }],
    [
      "@scalar/docusaurus",
      {
        label: "Server REST API",
        route: "/api/rest",
        showNavLink: false,
        configuration: {
          url: "/docs/api/fishjam-server-openapi.yaml",
          hideSearch: true,
          persistAuth: true,
          defaultOpenFirstTag: false,
          authentication: {
            preferredSecurityScheme: "management_token",
          },
        },
      } as ScalarOptions,
    ],
    [
      "docusaurus-plugin-typedoc",
      {
        id: "web-api",
        out: "docs/api/web",
        entryPoints: [
          "./packages/web-client-sdk/packages/react-client/src/index.ts",
        ],
        tsconfig:
          "./packages/web-client-sdk/packages/react-client/tsconfig.json",
        ...typedocConfig,
      },
    ],
    [
      "docusaurus-plugin-typedoc",
      {
        id: "mobile-api",
        out: "docs/api/mobile",
        entryPoints: [
          "./packages/web-client-sdk/packages/mobile-client/src/index.ts",
        ],
        tsconfig:
          "./packages/web-client-sdk/packages/mobile-client/tsconfig.json",
        ...typedocConfig,
      },
    ],
    [
      "docusaurus-plugin-typedoc",
      {
        id: "server-api",
        out: "docs/api/server",
        entryPoints: [
          "./packages/js-server-sdk/packages/js-server-sdk/src/index.ts",
        ],
        tsconfig:
          "./packages/js-server-sdk/packages/js-server-sdk/tsconfig.json",
        ...typedocConfig,
      },
    ],
    [
      "docusaurus-plugin-llms",
      {
        generateLLMsTxt: true,
        generateLLMsFullTxt: true,
        processingBatchSize: 8,
        title: "Fishjam Docs",
        description:
          "Fishjam is a low-latency video conferencing and live streaming API created by Software Mansion. It lets developers build real-time video, audio, and data streaming applications using WebRTC without needing any WebRTC expertise.",
        includeOrder: [
          "tutorials/**/*.{md,mdx}",
          "how-to/**/*.{md,mdx}",
          "explanation/**/*.{md,mdx}",
          "integrations/**/*.{md,mdx}",
          "api/reference.{md,mdx}",
          "api/mobile/index.{md,mdx}",
          "api/web/index.{md,mdx}",
          "api/server/index.{md,mdx}",
        ],
        ignoreFiles: ["**/type-aliases/**", "**/_common/**"],
        includeUnmatchedLast: false,
        excludeImports: true,
        removeDuplicateHeadings: true,
        rootContent: llmsRootContent,
      },
    ],
  ],
};

export default config;
