import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Welcome",
    },
    {
      type: "autogenerated",
      dirName: ".", // Generate sidebar from docs directory
    },
  ],
};

export default sidebars;
