import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
  // The MoQ docs get their own top-bar tab; this sidebar backs it. It surfaces
  // the Concepts and Tutorials categories under docs/moq. The docs are excluded
  // from `docsSidebar` in `sidebarItemsGenerator` so they only show here.
  moqSidebar: [
    {
      type: "autogenerated",
      dirName: "moq",
    },
  ],
};

export default sidebars;
