import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
  apiSidebar: [
    {
      type: "category",
      label: "API Reference",
      collapsible: false,
      link: {
        type: "generated-index",
        slug: "/api",
        description: "API documentation for Client and Server SDKs.",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "api",
        },
      ],
    },
  ],
};

export default sidebars;
