name: Static checks
on:
  pull_request:
jobs:
  types_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: init and update submodules
        run: git submodule update --init --recursive
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Use corepack
        run: corepack enable
      - name: Run prepare
        run: scripts/prepare.sh
      - name: Install node dependencies
        run: yarn --immutable
      - name: Spellcheck
        run: yarn spellcheck
      - name: Check formatting
        run: yarn format:check
      - name: Check types
        run: yarn typecheck
      - name: Check build
        run: yarn build
